version: "3.1"
services:
    warehouse_cloning:
        build: ./warehouse_cloning
        image: warehouse_cloning:2.2

        depends_on:
        - warehouse_mongo

    
    warehouse_mongo:
        build: ./warehouse_mongo
        image: warehouse_mongo:1.0
        
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: Admin123

        ports:
            - "27017:27017"

    mongo-express:
        image: mongo-express:latest

        restart: always

        environment:
            ME_CONFIG_MONGODB_SERVER: warehouse_mongo
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: Admin123
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: Admin123
         
        ports:
            - 8080:8081
            
        depends_on:
            - warehouse_mongo